In [1]:
import pandas as pd
import numpy as np

In [407]:
df = pd.read_csv("C:/Users/Vidhut Sharma/Downloads/ShortenedDelayFlight (1).csv")
df

,Unnamed: 0,ID,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,0,2008,1,3,4,1829,1755,1959,1925,...,3,10,0,N,0,2,0,0,0,32
1,1,1,2008,1,3,4,1937,1830,2037,1940,...,3,7,0,N,0,10,0,0,0,47
2,2,2,2008,1,3,4,1644,1510,1845,1725,...,6,8,0,N,0,8,0,0,0,72
3,3,3,2008,1,3,4,1452,1425,1640,1625,...,7,8,0,N,0,3,0,0,0,12
4,4,4,2008,1,3,4,1323,1255,1526,1510,...,4,9,0,N,0,0,0,0,0,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685729,685729,685729,2008,6,13,5,1609,1535,1942,1915,...,7,15,0,N,0,27,0,0,0,0
685730,685730,685730,2008,6,14,6,1616,1535,1954,1915,...,11,11,0,N,0,11,0,0,0,28
685731,685731,685731,2008,6,17,2,1617,1535,2002,1915,...,7,17,0,N,0,0,22,5,0,20
685732,685732,685732,2008,6,22,7,1607,1535,1941,1915,...,5,12,0,N,0,1,0,0,0,25
685733,685733,685733,2008,6,23,1,1608,1535,1933,1915,...,6,10,0,N,0,18,0,0,0,0

In [408]:
ListDest = {}
for name in df["Origin"].unique():
    Data = df[df["Origin"] == name]
    if any(Data["Dest"] == "0"):
        for i in Data["ID"]:
            if Data["Dest"][i] == "0":
                ListDest[i] = Data[Data["Distance"] == Data["Distance"][i]]["Dest"].unique()[0]

In [409]:
#Sorting Dict
myKeys = list(ListDest.keys())
myKeys.sort()
sorted_dict = {i: ListDest[i] for i in myKeys}
#sorted_dict

In [410]:
#Filling the missing destination in ListDataSort list 
df2 = df[df["Dest"] == "0"]
ListDataSort = []
for i in range(0,len(sorted_dict)):
    if list(sorted_dict.keys())[i] in df2["ID"]:
        ListDataSort.append(list(sorted_dict.values())[i])

In [412]:
#Filling the missing Destination values in df2
df2["Dest"] = ListDataSort
df2[["ID","Origin","Dest","Distance"]]

C:\Users\VIDHUT~1\AppData\Local\Temp/ipykernel_13260/3996090740.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Dest"] = ListDataSort

            ID Origin Dest  Distance
15050    15050    TPA  RDU       587
30100    30100    MSY  LGA      1183
45150    45150    SLC  DEN       391
60200    60200    MDW  SFO      1855
75250    75250    SFO  SNA       372
90300    90300    DCA  MEM       762
105350  105350    MIA  ORD      1197
120400  120400    FLL  JFK      1069
135450  135450    PDX  RNO       444
150500  150500    IAD  SAV       515
165550  165550    SFO  SLC       599
180600  180600    RDU  PHL       336
195650  195650    HPN  MCO       972
210700  210700    DCA  BOS       399
225750  225750    DFW  CHS       987
240800  240800    JFK  BUF       301
255850  255850    MSY  HOU       303
270900  270900    HOU  BHM       570
285950  285950    CVG  SAT      1024
301000  301000    ORD  LGA       733
316050  316050    HPN  ATL       780
331100  331100    DFW  XNA       281
346150  346150    HPN  DTW       505
361200  361200    DFW  IAD      1172
376250  376250    HNL  ATL      4502
391300  391300    PHL  BNA       675
406350  406350    MCI  CVG       539
421400  421400    MCO  LAS      2039
436450  436450    BOS  BWI       370
451500  451500    DTW  SBN       157
466550  466550    BOS  MCO      1121
481600  481600    ABQ  PHX       328
496650  496650    JAX  IAH       817
511700  511700    MRY  SFO        77
526750  526750    ATL  BDL       859
541800  541800    BOS  LGA       185
556850  556850    DFW  DCA      1192
571900  571900    JFK  MCO       944
586950  586950    TUS  LAX       451
602000  602000    LFT  IAH       201
617050  617050    TYS  ORD       475
632100  632100    PHX  DEN       602
647150  647150    PHL  ATL       665
662200  662200    ORD  FWA       157
677250  677250    ORD  STL       258

In [415]:
#Filling the Destination column in the main dataframe
for i in df2["ID"]:
    df.loc[i] = df2.loc[i]